name: flutter_chatgpt_sample
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  auto_route: ^6.4.0
  cupertino_icons: ^1.0.2
  dio: ^5.1.1
  flutter:
    sdk: flutter
  flutter_chat_types: ^3.6.0
  flutter_chat_ui: ^1.6.6
  flutter_hooks: ^0.18.6
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.4.0
  freezed_annotation: ^2.2.0
  hooks_riverpod: ^2.3.6
  intl: ^0.17.0
  package_info_plus: ^3.1.2
  retrofit: ^4.0.1
  shared_preferences: ^2.1.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^6.2.0
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  json_annotation: ^4.8.0
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  generate: true
