name: Test

env:
  FLUTTER_VERSION: 3.7.11

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}
          cache: true

      - name: flutter pub get
        run: |
          flutter pub get
      - name: flutter format
        run: |
          flutter format --dry-run --set-exit-if-changed .
      - name: flutter analyze
        run: |
          flutter analyze
